version: "3"
services:
  proxy:
    image: kobalt/dante-hostpam:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 200M
      restart_policy:
        condition: on-failure
    volumes:
      - "~/docker/dante/dante.pwdfile:/etc/dante.pwdfile:ro"
    ports:
      - "1080:1080"
    networks:
      - webnet
networks:
  - webnet:
