version: "3.5"
services:
  proxy:
    image: kobalt/dante-hostpam:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 200M
      restart_policy:
        condition: on-failure
    volumes:
      - "./dante.pwdfile:/etc/dante.pwdfile:ro"
    networks:
      hostnet: {}
networks:
  hostnet:
    external: true
    name: host
